[7] Get data from API
giorgian96/coffee-shop-finder pull request #2
Opened 2021-11-03 15:39 UTC by giorgian96

2021-11-03 16:04 UTC, dasilvaluis requested changes

2021-11-03 16:04 UTC, dasilvaluis commented on src/components/Map/Map.js
> +    latitude: 45,
About magic numbers, what happens if the canvas size changes?

2021-11-03 16:04 UTC, dasilvaluis commented on src/services/apiService.js
> +        if (apiKey !== '') {
This logic is all good in the case that the apiKey is not valid.
But following the logic from the start of the function until here, I understand that it is not possible to even call the API without the API key, as you always get it from the start. 
Is there a case where this function is called with different api keys, or keys fetched from memory?

2021-11-03 16:04 UTC, dasilvaluis commented on src/services/apiService.js
> +    let response = await fetch(`${this.BASE_API_URL}${this.GET_TOKEN}`, {
I don't understand why use let, when the value is not changed at all

2021-11-03 16:04 UTC, dasilvaluis commented on src/services/apiService.js
> +  async getCoffeeShops(apiKey = '') {
Argument values should not be reassigned, because then it becomes unpredictable what values do they have

2021-11-03 16:14 UTC, adrianbunea requested changes

2021-11-03 16:14 UTC, adrianbunea commented on src/components/Map/Map.js
> +    }
Would be nice to have this function extracted outside of the `useEffect`, this makes the function reusable, and doesn't bloat the `useEffect`, making it easier to read.

2021-11-03 16:14 UTC, adrianbunea commented on src/services/apiService.js
> +    console.log("Getting the coffee shops...");
Console logs no longer make sense in this situation, it made sense for a console app. You can use the state of the request to check if it is still loading or it gave an error and display the corresponding HTML. (But this is a bit more advanced so leave it for now, as it is just nice to have)

2021-11-03 16:14 UTC, adrianbunea commented on src/services/apiService.js
> +  validateValues(latitude, longitude) {
`validateValues` is a bit vague, it is clearly validating coordinates.

2021-11-03 16:14 UTC, adrianbunea commented on src/services/apiService.js
> +  validateValues(latitude, longitude) {
Also, this will make sense when you do the input form, not right now. Always try to stick to the subject when working on a PR.

2021-11-04 09:59 UTC, adrianbunea requested changes

2021-11-04 09:59 UTC, adrianbunea commented on src/components/Map/Map.js
> +}
If this dataValidation function would only do validating, instead of also fetching data, you wouldn't need to pass the `setCoffeeShopsFn` to it.

2021-11-04 10:05 UTC, merged